settings:
  title: '服务器状态'
  url: 'https://cf-workers-status-page-production.2240001733.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '服务器正常运行'
  notAllmonitorsOperational: '服务器都未运行'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '离线'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: '次断线' # xx incident(s) recorded

monitors:
  - id: dl-vikarna-top
    name: 阿晴
    description: '查看服务器是否在线'
    url: 'https://dl.vikarna.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
