export const locations = {
  ADL: 'Adelaide',
  AKL: '奥克兰',
  ALG: 'Algiers',
  AMM: 'Amman',
  AMS: '阿姆斯特丹',
  ARI: 'Arica',
  ARN: 'Stockholm',
  ASU: 'Asunción',
  ATH: '雅典',
  ATL: '亚特兰大',
  BAH: 'Manama',
  BCN: '巴塞罗那',
  BEG: '贝尔格莱德',
  BEL: 'Belém',
  BEY: '贝鲁特',
  BGW: '巴格达',
  BKK: '曼谷',
  BLR: 'Bangalore',
  BNA: 'Nashville',
  BNE: '布里斯班',
  BNU: 'Blumenau',
  BOG: '波哥大',
  BOM: '孟买',
  BOS: '波士顿',
  BRU: '布鲁塞尔',
  BSB: 'Brasilia',
  BUD: 'Budapest',
  BUF: '布法罗',
  BWN: 'Bandar Seri Begawan',
  CAN: '广州',
  CBR: '堪培拉',
  CCU: 'Kolkata',
  CDG: '巴黎',
  CEB: 'Cebu',
  CFC: 'Caçador',
  CGK: '雅加达',
  CGO: '郑州',
  CGP: 'Chittagong',
  CKG: '重庆',
  CLT: 'Charlotte',
  CMB: 'Colombo',
  CMH: 'Columbus',
  CMN: 'Casablanca',
  CNF: 'Belo Horizonte',
  CPH: 'Copenhagen',
  CPT: '开普敦',
  CSX: '株洲',
  CTU: '成都',
  CUR: 'Willemstad',
  CWB: 'Curitiba',
  DAC: '达卡',
  DAR: 'Dar Es Salaam',
  DEL: '新德里',
  DEN: 'Denver',
  DFW: '达拉斯',
  DKR: 'Dakar',
  DME: '莫斯科',
  DMM: 'Dammam',
  DOH: 'Doha',
  DTW: 'Detroit',
  DUB: '都柏林',
  DUR: 'Durban',
  DUS: 'Düsseldorf',
  DXB: '迪拜',
  EDI: '爱丁堡',
  EVN: '埃里温',
  EWR: 'Newark',
  EZE: 'Buenos Aires',
  FCO: '罗马',
  FLN: 'Florianopolis',
  FOR: 'Fortaleza',
  FRA: '法兰克福',
  GIG: 'Rio de Janeiro',
  GND: 'St. George’s',
  GOT: 'Gothenburg',
  GRU: '圣保罗',
  GUA: 'Guatemala City',
  GVA: '日内瓦',
  GYD: '巴库',
  GYE: 'Guayaquil',
  HAM: '汉堡',
  HAN: 'Hanoi',
  HEL: 'Helsinki',
  HKG: 'Hong Kong ',
  HNL: 'Honolulu',
  HRE: 'Harare',
  HYD: 'Hyderabad',
  IAD: 'Ashburn',
  IAH: '休斯顿',
  ICN: '首尔',
  IND: 'Indianapolis',
  ISB: '伊斯兰堡',
  IST: '伊斯坦布尔',
  ITJ: 'Itajaí',
  JAX: 'Jacksonville',
  JIB: 'Djibouti City',
  JNB: '约翰内斯堡',
  JSR: 'Jashore',
  KBP: '基辅',
  KEF: 'Reykjavík',
  KGL: 'Kigali',
  KHI: '卡拉奇',
  KIV: 'Chișinău',
  KIX: '大阪',
  KJA: 'Krasnoyarsk',
  KTM: 'Kathmandu',
  KUL: 'Kuala Lumpur',
  KWI: '科威特城',
  LAD: '卢安达',
  LAS: '拉斯维加斯',
  LAX: '洛杉矶',
  LCA: '尼科西亚',
  LED: '圣彼得堡',
  LHE: '拉合尔',
  LHR: '伦敦',
  LIM: '利马',
  LIS: '里斯本',
  LOS: '拉各斯',
  LUX: 'Luxembourg City',
  MAA: 'Chennai',
  MAD: '马德里',
  MAN: '曼彻斯特',
  MBA: '蒙巴萨',
  MCI: '堪萨斯城',
  MCT: 'Muscat',
  MDE: 'Medellín',
  MEL: 'Melbourne',
  MEM: '孟菲斯',
  MEX: '墨西哥城',
  MFE: 'McAllen',
  MFM: '澳门',
  MGM: 'Montgomery',
  MIA: '迈阿密',
  MLE: 'Malé',
  MNL: '马拉尼',
  MPM: 'Maputo',
  MRS: 'Marseille',
  MRU: 'Port Louis',
  MSP: 'Minneapolis',
  MUC: '慕尼黑',
  MXP: '米兰',
  NAG: 'Nagpur',
  NBG: '宁波',
  NBO: 'Nairobi',
  NOU: 'Noumea',
  NRT: '东京',
  OMA: 'Omaha',
  ORD: '芝加哥',
  ORF: 'Norfolk',
  OSL: '奥斯陆',
  OTP: '布加勒斯特',
  PAP: 'Port',
  PBH: 'Thimphu',
  PBM: 'Paramaribo',
  PDX: 'Portland',
  PER: '珀斯',
  PHL: '费城',
  PHX: '凤凰城',
  PIT: '匹兹堡',
  PMO: '巴勒莫',
  PNH: 'Phnom Penh',
  POA: 'Porto Alegre',
  PRG: 'Prague',
  PTY: '巴拿马城',
  QRO: 'Queretaro',
  QWJ: 'Americana',
  RAO: 'Ribeirao Preto',
  RGN: 'Yangon',
  RIC: '里士满',
  RIX: 'Riga',
  ROB: 'Monrovia',
  RUH: 'Riyadh',
  RUN: 'Réunion',
  SAN: '圣迭戈',
  SCL: '圣地亚哥',
  SEA: '西雅图',
  SGN: 'H胡志明市',
  SHA: '上海',
  SIN: '新加坡',
  SJC: 'San Jose',
  SJO: 'San José',
  SJP: 'São José do Rio Preto',
  SKG: '塞萨洛尼基',
  SLC: '盐湖城',
  SMF: 'Sacramento',
  SOD: 'Sorocaba',
  SOF: '索菲亚',
  SSA: '萨尔瓦多',
  STL: 'St. Louis',
  SVX: '叶卡捷琳娜堡',
  SYD: '悉尼',
  SZV: '苏州',
  TBS: '第比利斯',
  TGU: 'Tegucigalpa',
  TLH: 'Tallahassee',
  TLL: 'Tallinn',
  TLV: 'Tel Aviv',
  TNA: '济南',
  TNR: 'Antananarivo',
  TPA: 'Tampa',
  TPE: '台北 ',
  TSN: '天津',
  TUN: '突尼斯',
  TXL: '柏林',
  UIO: 'Quito',
  ULN: 'Ulaanbaatar',
  URT: 'Surat Thani',
  VCP: 'Campinas',
  VIE: '维也纳',
  VNO: '维尔纽斯',
  VTE: '万象',
  WAW: '华沙',
  WUH: '武汉',
  WUX: '无锡',
  XIY: '西安',
  YUL: '蒙特利尔',
  YVR: '温哥华',
  YWG: 'Winnipeg',
  YXE: 'Saskatoon',
  YYC: 'Calgary',
  YYZ: '多伦多',
  ZAG: 'Zagreb',
  ZDM: 'Ramallah ',
  ZRH: 'Zürich',
}
